# name: Commento++
# description: Enhanced fork of Commento providing additional features for moderation and wildcard domains.
# category: comments
# tags: comments, moderation, postgres, fork
# website: https://github.com/caroga/commentoplusplus
# docs: https://github.com/caroga/commentoplusplus#readme
# repo: https://github.com/caroga/commentoplusplus
---
services:
  commentoplusplus:
    image: caroga/commentoplusplus:v1.8.7
    ports:
      - "8080"
    environment:
      - COMMENTO_ORIGIN=${COMMENTO_ORIGIN}
      - COMMENTO_POSTGRES=${COMMENTO_POSTGRES}
      - COMMENTO_ENABLE_WILDCARDS=true
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
