# name: Budge
# description: A budgeting personal finance app.
# category: finance
# tags: personal-finance, budgeting, expenses, linuxserver
# website: https://www.linuxserver.io
# docs: https://github.com/linuxserver/docker-budge#readme
# repo: https://github.com/linuxserver/docker-budge
---
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    environment:
      - SERVICE_URL_BUDGE
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - budge-config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15
