# name: Checkcle
# description: Web-based platform for bookkeeping/financial checks (Operacle Checkcle) â€” simple self-hosted accounting UI.
# category: finance
# tags: bookkeeping, finance, accounting, web, self-hosted
# website: https://operacle.io
# docs: https://operacle.io/docs
# repo: https://github.com/operacle/checkcle
---
#Default id pass Username: admin@example.com Password: Admin123456
services:
  checkcle:
    image: operacle/checkcle:latest
    restart: unless-stopped
    expose:
      - 8090
    volumes:
      - checkcle-data:/mnt/pb_data
    ulimits:
      nofile:
        soft: 4096
        hard: 8192

volumes:
  checkcle-data: {}
