# name: Baserow
# description: Open-source no-code database and Airtable alternative for building collaborative database-backed apps.
# category: database
# tags: no-code, airtable, database, postgres, collaboration
# website: https://baserow.io
# docs: https://baserow.io/docs
# repo: https://github.com/baserow/baserow
---
services:
  baserow:
    image: baserow/baserow:1.25.2
    environment:
      BASEROW_PUBLIC_URL: "http://${BASEROW_HOST}"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
