# name: Duplicati
# description: Duplicati is a backup solution, allowing you to make scheduled backups with encryption.
# category: storage
# tags: backup,encryption,backup-software
# website: https://www.duplicati.com
# docs: https://duplicati.readthedocs.io
# repo: https://github.com/duplicati/duplicati
---
services:

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - SERVICE_URL_DUPLICATI_8200
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/London}
      - SETTINGS_ENCRYPTION_KEY=${SERVICE_PASSWORD_ENCRYPT}
      - DUPLICATI__WEBSERVICE_PASSWORD=${SERVICE_PASSWORD_WEB}
    volumes:
      - duplicati-config:/config
      - duplicati-backups:/backups
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8200"]
      interval: 2s
      timeout: 10s
      retries: 15
