services:

  vaultwarden:
    image: vaultwarden/server:latest
    hostname: vaultwarden
    container_name: vaultwarden
    # security options optional - uncomment if required
    # security_opt:
    #   - apparmor:unconfined
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://vaultwarden:80 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_TIMEOUT: ${SMTP_TIMEOUT}
      DOMAIN: ${DOMAIN}
    networks:
      - vaultwarden
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - vaultwarden-data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  vaultwarden:
    name: vaultwarden
    driver: bridge
