#file: noinspection ComposeUnknownValues
---
networks:
  1panel-network:
    external: true

services:
  ntfy:
    command:
      - serve
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      - TZ=${TIME_ZONE}
    healthcheck:
      interval: 60s
      retries: 3
      start_period: 40s
      test:
        - CMD-SHELL
        - wget -q --tries=1 http://localhost:${APP_PORT_INTERNAL}/v1/health -O - | grep -Eo '"healthy"\s*:\s*true' || exit 1
      timeout: 10s
    image: binwiederhier/ntfy:latest
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:${APP_PORT_INTERNAL}
    restart: always
    security_opt:
      - apparmor:unconfined
    user: ${PUID}:${PGID}
    volumes:
      - /mnt/dkvol/dk1/ntfy/data/cache/ntfy:/var/cache/ntfy
      - /mnt/dkvol/dk1/ntfy/data/ntfy:/etc/ntfy
