# name: Calibre-Web
# description: Web app to browse, read and manage Calibre ebook libraries with a clean web UI.
# category: books
# tags: ebooks, library, web-ui, calibre
# website: https://calibre-web.readthedocs.io
# docs: https://github.com/janeczku/calibre-web#readme
# repo: https://github.com/janeczku/calibre-web
---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - DOCKER_MODS=linuxserver/mods:universal-calibre # optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 # optional
    volumes:
      - calibre-config:/config
      - calibre-books:/books
      - ../files/startup-scripts:/custom-cont-init.d:ro # optional, comment out if you have your own metadata.db file, otherwise it will be created

volumes:
  calibre-config: {}
  calibre-books: {}
