# name: DokuWiki
# description: A lightweight and easy-to-use wiki platform for creating and managing documentation and knowledge bases.
# category: cms
# tags: wiki,documentation,knowledge,base,dokuwiki
# website: https://www.dokuwiki.org
# docs: https://www.dokuwiki.org/docs
# repo: https://github.com/splitbrain/dokuwiki
---
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    environment:
      - SERVICE_URL_DOKUWIKI
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - dokuwiki-config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15
