# name: CloudBeaver
# description: Web-based database management UI built on DBeaver for managing SQL and NoSQL databases.
# category: devtools
# tags: database, admin, sql, dbeaver, web-ui
# website: https://dbeaver.com/cloudbeaver
# docs: https://dbeaver.com/docs/cloudbeaver/
# repo: https://github.com/dbeaver/cloudbeaver
---
# documentation: https://dbeaver.com/docs/cloudbeaver/
# slogan: CloudBeaver is a lightweight web application designed for comprehensive data management.
# category: devtools
# tags: dbeaver, data management, data, database, mysql, postgres, sqlite, sql, mongodb
# port: 8978

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:24
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    environment:
      - SERVICE_URL_CLOUDBEAVER_8978
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8978/"]
      interval: 5s
      timeout: 20s
      retries: 10
