# name: Adminer
# description: Single-file database management tool for MySQL, PostgreSQL, SQLite and others.
# category: database
# tags: database, admin, mysql, postgres, sqlite, GUI
# website: https://www.adminer.org
# docs: https://www.adminer.org/#download
# repo: https://github.com/vrana/adminer
---
services:
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8080
