# name: Calibre (linuxserver)
# description: Calibre e-book management server packaged by LinuxServer for managing and serving ebook libraries.
# category: books
# tags: ebooks, library, calibre, linuxserver
# website: https://calibre-ebook.com
# docs: https://github.com/linuxserver/docker-calibre#readme
# repo: https://github.com/linuxserver/docker-calibre
---
services:
  calibre:
    image: linuxserver/calibre:7.26.0
    restart: unless-stopped
    environment:
      - PASSWORD=${PASSWORD}
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    ports:
      - 8080
    volumes:
      - books:/books
      - data:/config

volumes:
  books:
  data:
