# name: Double Zero
# description: Background job processing service with optional AWS SQS integration and local DB storage.
# category: worker
# tags: jobs,worker,background,aws,sqs,elixir
# website: https://hub.docker.com/r/liltechnomancer/double-zero
# docs: https://hub.docker.com/r/liltechnomancer/double-zero
# repo: https://github.com/liltechnomancer/double-zero
---
services:
  doublezero:
    restart: always
    image: liltechnomancer/double-zero:0.2.1
    volumes:
      - db-data:/var/lib/doublezero/data
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      SQS_URL: ${SQS_URL}
      SYSTEM_EMAIL: ${SYSTEM_EMAIL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${DOUBLEZERO_HOST}
      DATABASE_PATH: ./00.db

volumes:
  db-data:
    driver: local
