# name: Bitcoin Core
# description: A self-hosted Bitcoin Core full node.
# category: backend
# tags: cryptocurrency, node, blockchain, bitcoin
# website: https://bitcoincore.org
# docs: https://hub.docker.com/r/ruimarinho/bitcoin-core/
# repo: https://github.com/ruimarinho/docker-bitcoin-core
---
services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:latest
    environment:
      - BITCOIN_RPCUSER=${BITCOIN_RPCUSER:-bitcoinuser}
      - BITCOIN_RPCPASSWORD=${SERVICE_PASSWORD_PASSWORD64}
      - BITCOIN_PRINTTOCONSOLE=${BITCOIN_PRINTTOCONSOLE:-1}
      - BITCOIN_TXINDEX=${BITCOIN_TXINDEX:-1}
      - BITCOIN_SERVER=${BITCOIN_SERVER:-1}
    volumes:
      - blockchain-data:/home/bitcoin/.bitcoin
    command:
      [
        "-datadir=/home/bitcoin/.bitcoin",
        "-rpcbind=127.0.0.1", # only allow local connections
        "-rpcallowip=127.0.0.1",
        "-rpcuser=${BITCOIN_RPCUSER}",
        "-rpcpassword=${SERVICE_PASSWORD_PASSWORD64}",
        "-printtoconsole=${BITCOIN_PRINTTOCONSOLE}",
        "-txindex=${BITCOIN_TXINDEX}",
        "-server=${BITCOIN_SERVER}"
      ]
