# name: Bazarr
# description: Subtitle management and downloading companion for Sonarr/Radarr to automatically fetch and manage subtitles.
# category: media
# tags: subtitles, media, downloader, sonarr, radarr
# website: https://www.bazarr.media
# docs: https://github.com/morpheus65535/bazarr#readme
# repo: https://github.com/morpheus65535/bazarr
---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.1
    restart: unless-stopped
    ports:
      - 6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - config:/config
      - ${MOVIES_PATH}:/movies
      - ${TV_PATH}:/tv

volumes:
  config: {}
