services:

  postgres:
    image: postgres:16-alpine
    container_name: dockhand-postgres
    networks:
      - dockhand
    environment:
      POSTGRES_USER: dockhand
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dockhand
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    user: "0:0"
    networks:
      - dockhand
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://dockhand:${DB_PASSWORD}@postgres:5432/dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand-data:/app/data
    depends_on:
      - postgres

volumes:
  postgres-data:
    name: postgres-data
    driver: local
  dockhand-data:
    name: dockhand-data
    driver: local

networks:
  dockhand:
    name: dockhand
    driver: bridge
