# name: Directory Lister
# description: Simple web app to list directory contents and serve static files.
# category: utility
# tags: directory,lister,files,static,web
# website: https://directorylister.com
# docs: https://github.com/DirectoryLister/DirectoryLister#readme
# repo: https://github.com/DirectoryLister/DirectoryLister
---
services:
  directory-lister:
    image: directorylister/directorylister:latest
    restart: unless-stopped
    ports:
      # The internal port of the application.
      - 80
    volumes:
      # Mounts a persistent named volume to store directory data.
      - directory-lister-data:/data

volumes:
  # Defines the Docker-managed volume for data persistence.
  directory-lister-data: {}
