services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    user: "${PUID:-1000}:${PGID:-1000}"

    # Hardened runtime
    read_only: true
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      apprise:
        ipv4_address: ${IPV4_ADDRESS}
    ports:
      - "8000:8000"

    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: "1"
      APPRISE_ADMIN: "y"

    # Persistent state
    volumes:
      - ${BASEDIR}/config:/config
      - ${BASEDIR}/plugin:/plugin
      - ${BASEDIR}/attach:/attach

    # Ephemeral runtime and temp files
    tmpfs:
      - /tmp

networks:
  apprise:
    name: apprise
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
