# name: Cloud9 (linuxserver)
# description: Web-based IDE (Cloud9) packaged by LinuxServer for remote development in the browser.
# category: devtools
# tags: ide, cloud9, development, remote, linuxserver
# website: https://linuxserver.io
# docs: https://github.com/linuxserver/docker-cloud9
# repo: https://github.com/linuxserver/docker-cloud9
---
services:
  cloud9:
    image: lscr.io/linuxserver/cloud9:1.29.2
    ports:
      - "8000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - GITURL=https://github.com/linuxserver/docker-cloud9.git
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - code:/code

volumes:
  code:
